export const quotes = [
  { text: "El teatro es poesía que se hace humana", author: "Federico García Lorca" },
  { text: "Todo el mundo es un escenario", author: "William Shakespeare, As You Like It" },
  { text: "El teatro no puede desaparecer porque es el único arte donde la humanidad se enfrenta a sí misma", author: "Arthur Miller" },
  { text: "Actuar es vivir sinceramente bajo circunstancias imaginarias", author: "Sanford Meisner" },
  { text: "El teatro es un espejo en el que nos miramos todos", author: "Julio César (Shakespeare)" },
  { text: "El actor es un atleta del corazón", author: "Antonin Artaud" },
  { text: "Dame un punto fijo y moveré el mundo", author: "Arquímedes" },
  { text: "La vida es una obra sin ensayos", author: "Charles Chaplin" },
  { text: "En el teatro, el silencio tiene voz", author: "Peter Brook" },
  { text: "El teatro es la primera ficción de la humanidad", author: "Edward Gordon Craig" },
  { text: "El público es el actor final", author: "Bertolt Brecht" },
  { text: "El arte no es un espejo para reflejar la realidad, sino un martillo para darle forma", author: "Bertolt Brecht" },
  { text: "Hay que tener caos dentro de uno para dar a luz una estrella danzante", author: "Nietzsche" },
  { text: "Un actor debe vivir para poder interpretar", author: "Konstantin Stanislavski" },
  { text: "El teatro es la pasión de contar historias", author: "Peter Brook" },
  { text: "La actuación es la capacidad de comportarse de forma natural en circunstancias no naturales", author: "David Mamet" },
  { text: "El talento es entrega", author: "Uta Hagen" },
  { text: "El teatro es el arte del presente", author: "Jerzy Grotowski" },
  { text: "La imaginación es más importante que el conocimiento", author: "Albert Einstein" },
  { text: "El actor crea la vida; el director la hace visible", author: "Elia Kazan" },
  { text: "El teatro es el arte de mirar y de ser mirado", author: "Jean Genet" },
  { text: "El personaje nace cuando el actor se olvida de sí mismo", author: "Grotowski" },
  { text: "El teatro es el espacio donde lo imposible sucede", author: "Peter Brook" },
  { text: "Una obra es un misterio revelado", author: "Yasmina Reza" },
  { text: "El humor es la distancia más corta entre dos personas", author: "Victor Borge" },
  { text: "El escenario es mi piel", author: "Sarah Bernhardt" },
  { text: "La tragedia es imitación de una acción elevada", author: "Aristóteles, Poética" },
  { text: "La comedia es simplemente una tragedia que se niega a llorar", author: "Roberto Benigni" },
  { text: "Actuar es escuchar", author: "Alan Rickman" },
  { text: "No existe teatro sin conflicto", author: "George Bernard Shaw" },
  { text: "El actor debe ser un poeta del comportamiento", author: "Michael Chekhov" },
  { text: "La vida es teatro y el teatro es vida", author: "Jean-Louis Barrault" },
  { text: "Si no hay emoción, no hay arte", author: "Stanislavski" },
  { text: "Un personaje es un problema con piernas", author: "Tennessee Williams" },
  { text: "El público siempre tiene razón", author: "Charles Chaplin" },
  { text: "La comedia es tragedia más tiempo", author: "Mark Twain" },
  { text: "El teatro es el arte de convertir lo cotidiano en extraordinario", author: "Lee Strasberg" },
  { text: "Un actor se mide por sus silencios", author: "Robert De Niro" },
  { text: "El teatro vuelve visible lo invisible", author: "Peter Shaffer" },
  { text: "El teatro debería incomodar", author: "Bertolt Brecht" },
  { text: "El teatro no es literatura: es carne", author: "Heiner Müller" },
  { text: "El cuerpo del actor es su primer instrumento", author: "Grotowski" },
  { text: "Las palabras son buenas, pero el movimiento es mejor", author: "Pina Bausch" },
  { text: "Todo arte es una confesión", author: "Albert Camus" },
  { text: "El teatro es el arte de compartir el alma", author: "Laurence Olivier" },
  { text: "Si uno puede reírse de sí mismo, está a salvo", author: "Oscar Wilde" },
  { text: "La risa es un acto de resistencia", author: "Dario Fo" },
  { text: "La obra vive solo en el instante", author: "Peter Brook" },
  { text: "Un actor debe amar la duda", author: "Yoshi Oida" },
  { text: "La autenticidad es más valiosa que la técnica", author: "Uta Hagen" },
  { text: "El escenario es el lugar donde todo puede suceder", author: "Peter Brook" },
  { text: "Un buen actor no imita: revela", author: "Michael Chekhov" },
  { text: "El drama es conflicto", author: "Aristóteles" },
  { text: "La pasión hace al actor", author: "Sarah Bernhardt" },
  { text: "No hay papeles pequeños, solo actores pequeños", author: "Stanislavski" },
  { text: "Un personaje es una puerta hacia un mundo", author: "Caryl Churchill" },
  { text: "La obra termina cuando el espectador quiere", author: "Jean-Luc Godard" },
  { text: "El teatro es el reino de la contradicción", author: "Antonin Artaud" },
  { text: "La verdad es el mejor espectáculo", author: "William Shakespeare" },
  { text: "El actor debe ser valiente", author: "Tennessee Williams" },
  { text: "Actuar es exponerse sin protección", author: "Al Pacino" },
  { text: "La escena es el laboratorio de la humanidad", author: "Peter Brook" },
  { text: "La tragedia limpia el alma", author: "Aristóteles" },
  { text: "La risa es una confesión involuntaria", author: "Mark Twain" },
  { text: "El teatro nace del ritual", author: "Victor Turner" },
  { text: "La máscara revela lo que la cara oculta", author: "Jacques Lecoq" },
  { text: "Improvisar es confiar", author: "Keith Johnstone" },
  { text: "La ficción es la hermana mayor de la verdad", author: "George Steiner" },
  { text: "El teatro es un acto de fe", author: "Peter Brook" },
  { text: "Actuar es recordar lo olvidado", author: "Miguel Ángel Solá" },
  { text: "La emoción es el puente entre actor y público", author: "Lee Strasberg" },
  { text: "Mate al personaje, viva el actor", author: "Heiner Müller" },
  { text: "El teatro es política sin discurso", author: "Bertolt Brecht" },
  { text: "No actuamos para ser vistos, sino para ser entendidos", author: "Viola Spolin" },
  { text: "Cada función es una vida nueva", author: "Laurence Olivier" },
  { text: "El drama empieza donde terminan las palabras", author: "Harold Pinter" },
  { text: "El actor trabaja con memoria y deseo", author: "Pina Bausch" },
  { text: "Una obra es un viaje emocional", author: "Arthur Miller" },
  { text: "Todo personaje tiene un secreto", author: "Tennessee Williams" },
  { text: "La escena es un ritual compartido", author: "Jerzy Grotowski" },
  { text: "El teatro es un acto de amor", author: "Peter Brook" },
  { text: "El cuerpo nunca miente", author: "Martha Graham" },
  { text: "La imaginación lo es todo", author: "Einstein" },
  { text: "La tragedia necesita belleza", author: "Eurípides" },
  { text: "La comedia necesita precisión", author: "Charlie Chaplin" },
  { text: "Actuar es un acto de vulnerabilidad extrema", author: "Kate Winslet" },
  { text: "La verdad del personaje nace de la escucha", author: "Meisner" },
  { text: "El teatro es memoria viva", author: "Arias Patricia" },
  { text: "Las emociones son el verdadero texto", author: "Uta Hagen" },
  { text: "La obra pertenece al público", author: "Peter Brook" },
  { text: "El actor es el puente entre la ficción y la vida", author: "Michael Chekhov" },
  { text: "El teatro es una celebración de lo humano", author: "Ariane Mnouchkine" },
  { text: "No hay nada más serio que la comedia", author: "Roberto Benigni" },
  { text: "Actuar es jugar", author: "Viola Spolin" },
  { text: "El miedo es combustible", author: "Grotowski" },
  { text: "Un actor debe amar lo desconocido", author: "Peter Brook" },
  { text: "Todo gran teatro surge del riesgo", author: "Antonin Artaud" },
  { text: "La obra respira si vos respirás", author: "Lee Strasberg" },
  { text: "La escena es un mapa emocional", author: "Julian Beck" },
  { text: "El teatro es el arte más vivo de todos", author: "Laurence Olivier" }
];

export function getRandomQuote() {
  const index = Math.floor(Math.random() * quotes.length);
  return quotes[index];
}
